added
scade-platform/FusionExamples pull request #3
Opened 2021-07-22 20:02 UTC by pavloboiko

2021-07-22 20:02 UTC, pavloboiko commented
added bluetooth example

2021-07-30 10:21 UTC, gr-markin requested changes

2021-07-30 10:21 UTC, gr-markin commented on BluetoothApp/Sources/BluetoothApp/main.page.swift
> +      self.checkState()
I asked this in the API topic, here, if one wants to change the label text based on the authorisation results, can one just do a request with a authorisation callback without using check

2021-09-23 18:01 UTC, gr-markin approved these changes

2021-09-23 18:01 UTC, merged